### ISSUE TITLE
dvg_pyqt_filelogger.py / file missing?

### ISSUE THREAD

**Issue by rsxy** [Dennis-van-Gils/DvG_Arduino_lock-in_amp#45]
Hi, I came across your project which really looks awesome! Thanks for sharing!

After cloning the repo I tried to start the main program DvG_Arduino_lockin_amp.py and got the following error:

line 23: from dvg_pyqt_filelogger import FileLogger
ModuleNotFoundError: No module named 'dvg_pyqt_filelogger'

Apparently this file is currently not part of the repo.

**Comment by rsxy** [comment]
..OK, I figured that I have to install some other packages of yours, i.e.:

pip3 install dvg_devices       # dgv_pyqt_filelogger and others will be installed as dependency
pip3 install dvg_pyqtgraph_monkeypatch
pip3 install pyopengl

..finally, I got a UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-14: character maps to <undefinded>
..which could be resolved by launching the program with:
python **-X utf8** DvG_Arduino_lockin_amp.py

..now up and running!  :-D

(Win10 with Anaconda and Python 3.9.7)

**Comment by Dennis-van-Gils** [comment]
Hi @rsxy. Sorry I missed your message. Glad you have it working, but you probably could have saved yourself above troubles by following the install guide mentioned in [HOWTO_INSTALL.txt](https://github.com/Dennis-van-Gils/DvG_Arduino_lock-in_amp/blob/master/HOWTO_INSTALL.txt) or examining the [user manual](https://github.com/Dennis-van-Gils/DvG_Arduino_lock-in_amp/blob/master/user_manual/DvG_ALIA_Student_user_manual.pdf)
